### ISSUE TITLE
modmore's icon seems to be missing

### ISSUE THREAD

**Issue by enigmatic-user** [modmore/QuickstartButtons#48]
modmore's icon seems to be missing, it's neither shown in the list of icons (the name is there) nor on the example button.

**Comment by sebastian-marinescu** [comment]
I can also see this. Looking into it, all icons used are font-awesome icons. They use the FA css-styles. 
The modmore-icon however has the class "icon" and is integrated as background-image.
This image also exists in the package, problem is, the icon-element has no height/width, that's why it is not shown. 

Something like this will fix it: 
```css
    width: 1.28571429em;
    height: 1em;
    background-size: contain;
    background-repeat: no-repeat;
    background-position: center;
```
Also in my opinion the icons in the list should all get the "fa-fw" (fixed-width) class, so the titles of the icons all start at the same horizontal position.

**Comment by Mark-H** [comment]
Thanks for saving me time having to figure out appropriate styles for that fix @sebastian-marinescu

**Comment by sebastian-marinescu** [comment]
You're welcome @Mark-H 🤟
